theme: jekyll-theme-cayman
title: Cost of Buying/Renting Algorithm (COBRA)
description: COBRA is a front-end web client application framework, with core functionality that is geared in support of LA Team (Dava & Visual Analystics) and built on the Pyramid framework.
